version: "3.7"

services:

  neosvr:
    build: .
    environment:
      LAUNCH_APP: 740250
      INSTALL_APPS: 740250
      STEAM_USER: ${STEAM_USER}
      STEAM_PWD: ${STEAM_PWD}
      STEAM_BETA_NAME: headless-client
      STEAM_BETA_KEY: ${STEAM_BETAKEY}
      NEOSVR_USER: ${NEOSVR_USER}
      NEOSVR_PWD: ${NEOSVR_PWD}
    volumes:
      - ./steam:/steam
      - ./logs:/logs
      - ./config:/steam/740250/Config
    stdin_open: true
    tty: true
