version: "3.7"

services:

  neosvr:
    build: .
    environment:
      LAUNCH_APP: 740250
      INSTALL_APPS: 740250
      LOGIN: user
      PASSWORD: pwd
      BETA_NAME: headless-client
      BETA_KEY: ***
    volumes:
      - ./steam:/steam
      - ./logs:/logs
      - ./config:/steam/740250/Config:ro
    stdin_open: true
    tty: true
